### ISSUE TITLE
mean stack issue

### ISSUE THREAD

**Issue by meansean13** [ramitos/mean#1]
Hi,
I'm a total newbie trying to learn mean stack. I have gone through the installs and tried to trouble shoot as best I can, but I keep getting the error below. I suggests to include a npm-debug.log, but there doesn't seem to be one.

Thank you for your time and assistance,
-meansean13

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! mean@0.5.5 start: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mean@0.5.5 start script 'node server'.
npm ERR! This is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/SAMartin/mean/MyMeanApp/npm-debug.log

**Comment by sergioramos** [comment]
I think you're looking in the wrong repository: https://github.com/linnovate/mean

**Comment by meansean13** [comment]
Thanks. I fixed my problem and am up a running.
